### ISSUE TITLE
SagaAudit does populate InvokedSagas header for audit messages

### ISSUE THREAD

**Issue by boblangley** [Particular/ServiceControl.Plugin.Nsb6.SagaAudit#12]
Steps to reproduce:
- Update to latest ServiceControl / ServiceInsight
- Run Nsb6.SagaAudit SmokeTest Project
- Check for Saga Audit data in ServiceInsight

Saga diagrams are not produced.

**Comment by mikeminutillo** [comment]
@boblangley this works for me. I'm not sure if I am doing anything differently. I did notice that `SomeWorkIsComplete` events do not show the saga view when selected but everything else does. To be fair though, that comes from a stand-alone handler and not a Saga. I'll try it with the V5 plugin and see if it has the same issue.

![image](https://cloud.githubusercontent.com/assets/124014/18898822/b7376c08-8566-11e6-903e-cc8128ac34f2.png)

**Comment by mikeminutillo** [comment]
Actually those events are interesting. We used to have a header `NServiceBus.InvokedSagas` which SC uses  to determine which sagas have been invoked as a part of an audited message. This header no longer exists (since https://github.com/Particular/NServiceBus/issues/2183). If that header is not present, then we fall back to checking for a `NServiceBus.SagaId` header which gets added to Timeout messages. Finally, there is an `NServiceBus.OriginatingSagaId` header that gets added to all _outgoing_ messages coming from a saga. 

All of this means there is no reliable way (currently) to figure out if an incoming message (that is not a timeout) activated a saga or not. So we cannot show the saga view for a message that initiates or activates a saga.

**Comment by boblangley** [comment]
So, it turns out the populating of the `NServiceBus.InvokedSagas` was intended to be moved to the SagaAudit plugin but still resided in the core as of v5:

`[ObsoleteEx(RemoveInVersion = "6.0", TreatAsErrorFromVersion = "5.1", Message = "Enriching the headers for saga related information has been moved to the SagaAudit plugin in ServiceControl.  Add a reference to the Saga audit plugin in your endpoint to get more information.")]`
https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs#L145-L161

So in one way it IS the core that changed, but the intention to move it to the plugin was not followed through. We just ported the v5 plugin to v6, this additional task was not added to the scope.

I will implement that behavior in this version of the plugin to complete the intended migration.

**Comment by boblangley** [comment]
Created PR #13 that implements the InvokedSagas header population behavior

**Comment by boblangley** [comment]
I modified the [5 to 6 upgrade guide](https://docs.particular.net/nservicebus/upgrades/5to6/messaging) to add this change of behavior (from core to plugin).

**Comment by timbussmann** [comment]
closing this as the PR has been merged and is part of release 1.0.1
